model:
  repository_id: nguyenvulebinh/AV-HuBERT-CTC-Attention-VI
  revision: b8a1fa5d6079701b3f8f791bfd601057fbd23de3
  cache_dir: .cache/models
  device: cuda
  dtype: float32

tokenizer:
  model_path: assets/tokenizers/vi/unigram2048.model
  units_path: assets/tokenizers/vi/unigram2048_units.txt
